In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
pip install matplotlib

Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Ecommerce.csv")

In [ ]:
print(df)

          ID Warehouse_block Mode_of_Shipment  Customer_care_calls  \
0          1               D           Flight                    4
1          2               F           Flight                    4
2          3               A           Flight                    2
3          4               B           Flight                    3
4          5               C           Flight                    2
...      ...             ...              ...                  ...
10994  10995               A             Ship                    4
10995  10996               B             Ship                    4
10996  10997               C             Ship                    5
10997  10998               F             Ship                    5
10998  10999               D             Ship                    2

       Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                    2                  177                3
1                    5                  216                2
2                    2                  183                4
3                    3                  176                4
4                    2                  184                3
...                ...                  ...              ...
10994                1                  252                5
10995                1                  232                5
10996                4                  242                5
10997                2                  223                6
10998                5                  155                5

      Product_importance Gender  Discount_offered  Weight_in_gms  \
0                    low      F                44           1233
1                    low      M                59           3088
2                    low      M                48           3374
3                 medium      M                10           1177
4                 medium      F                46           2484
...                  ...    ...               ...            ...
10994             medium      F                 1           1538
10995             medium      F                 6           1247
10996                low      F                 4           1155
10997             medium      M                 2           1210
10998                low      F                 6           1639

       Reached.on.Time_Y.N
0                        1
1                        1
2                        1
3                        1
4                        1
...                    ...
10994                    1
10995                    0
10996                    0
10997                    0
10998                    0

[10999 rows x 12 columns]

In [ ]:
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [ ]:
df[df['Customer_rating']>3]

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
6,7,D,Flight,3,4,250,3,low,F,3,2371,1
8,9,A,Flight,3,4,150,3,low,F,11,1861,1
10,11,C,Flight,3,4,189,2,medium,M,12,2888,1
11,12,F,Flight,4,5,232,3,medium,F,32,3253,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10980,10981,D,Ship,4,4,261,5,low,F,4,1649,1
10986,10987,D,Ship,4,5,255,5,medium,M,5,1458,1
10990,10991,C,Ship,5,4,219,6,low,M,3,1098,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

In [ ]:
df.describe()

,ID,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
count,10999.00000,10999.000000,10999.000000,10999.000000,10999.000000,10999.000000,10999.000000,10999.000000
mean,5500.00000,4.054459,2.990545,210.196836,3.567597,13.373216,3634.016729,0.596691
std,3175.28214,1.141490,1.413603,48.063272,1.522860,16.205527,1635.377251,0.490584
min,1.00000,2.000000,1.000000,96.000000,2.000000,1.000000,1001.000000,0.000000
25%,2750.50000,3.000000,2.000000,169.000000,3.000000,4.000000,1839.500000,0.000000
50%,5500.00000,4.000000,3.000000,214.000000,3.000000,7.000000,4149.000000,1.000000
75%,8249.50000,5.000000,4.000000,251.000000,4.000000,10.000000,5050.000000,1.000000
max,10999.00000,7.000000,5.000000,310.000000,10.000000,65.000000,7846.000000,1.000000

In [ ]:
df['Salary'] = [50000, 60000, 70000]

ValueError: Length of values (3) does not match length of index (10999)

In [ ]:
df.loc[:2, 'Salary'] = [50000, 60000, 70000]

In [ ]:
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Salary
0,1,D,Flight,4,2,177,3,low,F,44,1233,1,50000.0
1,2,F,Flight,4,5,216,2,low,M,59,3088,1,60000.0
2,3,A,Flight,2,2,183,4,low,M,48,3374,1,70000.0
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1,NaN
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1,NaN

In [ ]:
df.head(3)

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Salary
0,1,D,Flight,4,2,177,3,low,F,44,1233,1,50000.0
1,2,F,Flight,4,5,216,2,low,M,59,3088,1,60000.0
2,3,A,Flight,2,2,183,4,low,M,48,3374,1,70000.0

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}
dff = pd.DataFrame(data)

In [ ]:
print(dff)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df.drop('Salary', axis=1)

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

In [ ]:
df.isnull().sum()

ID                         0
Warehouse_block            0
Mode_of_Shipment           0
Customer_care_calls        0
Customer_rating            0
Cost_of_the_Product        0
Prior_purchases            0
Product_importance         0
Gender                     0
Discount_offered           0
Weight_in_gms              0
Reached.on.Time_Y.N        0
Salary                 10996
dtype: int64

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(2, 2)

array([[0.81913098, 0.5276258 ],
       [0.42882533, 0.80880062]])

In [ ]:
df = np.read_csv(".csv")

In [ ]:
xd = np.mean(df['Discount_offered'])

In [ ]:
print(xd)

13.37321574688608

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Step 1: Load the data (Replace with your actual path if needed)
# df = pd.read_csv("your_file.csv")  # Uncomment if reading from CSV

# Sample DataFrame from your provided data
data = {
    'ID': [1, 2, 3, 4, 5],
    'Warehouse_block': ['D', 'F', 'A', 'B', 'C'],
    'Mode_of_Shipment': ['Flight'] * 5,
    'Customer_care_calls': [4, 4, 2, 3, 2],
    'Customer_rating': [2, 5, 2, 3, 2],
    'Cost_of_the_Product': [177, 216, 183, 176, 184],
    'Prior_purchases': [3, 2, 4, 4, 3],
    'Product_importance': ['low', 'low', 'low', 'medium', 'medium'],
    'Gender': ['F', 'M', 'M', 'M', 'F'],
    'Discount_offered': [44, 59, 48, 10, 46],
    'Weight_in_gms': [1233, 3088, 3374, 1177, 2484],
    'Reached.on.Time_Y.N': [1, 1, 1, 1, 1],
    'Salary': [50000.0, 60000.0, 70000.0, np.nan, np.nan]
}

df = pd.DataFrame(data)

# Step 2: Handle missing values
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

# Step 3: Drop unnecessary columns
df = df.drop('ID', axis=1)

# Step 4: Encode categorical columns
label_cols = ['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender']
le = LabelEncoder()

for col in label_cols:
    df[col] = le.fit_transform(df[col])

# Step 5: Split features and target
X = df.drop('Reached.on.Time_Y.N', axis=1)
y = df['Reached.on.Time_Y.N']

# Step 6: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 7: Train a Random Forest Classifier
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 8: Make predictions
y_pred = model.predict(X_test)

# Step 9: Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 1.0
Confusion Matrix:
 [[1]]
Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00         1

    accuracy                           1.00         1
   macro avg       1.00      1.00      1.00         1
weighted avg       1.00      1.00      1.00         1

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

In [ ]:
df['ID']

0            1
1            2
2            3
3            4
4            5
         ...
10994    10995
10995    10996
10996    10997
10997    10998
10998    10999
Name: ID, Length: 10999, dtype: int64